Repository TeamLapen/Vampirism, pull requests merged in 2019-06, with the labels that each got.

#439 adding village events & possible more
  src/api/java/de/teamlapen/vampirism/api/event/VampirismVillageEvent.java
  src/main/java/de/teamlapen/vampirism/entity/factions/FactionPlayerHandler.java
  src/main/java/de/teamlapen/vampirism/tileentity/TileTotem.java
  src/main/java/de/teamlapen/vampirism/util/ModEventFactory.java
Labels: modcompat

#442 Add permission checks
  src/api/java/de/teamlapen/vampirism/api/entity/player/actions/DefaultAction.java
  src/main/java/de/teamlapen/vampirism/VampirismMod.java
  src/main/java/de/teamlapen/vampirism/core/ModEventHandler.java
  src/main/java/de/teamlapen/vampirism/network/InputEventPacket.java
  src/main/java/de/teamlapen/vampirism/player/actions/ActionHandler.java
  src/main/java/de/teamlapen/vampirism/player/vampire/VampirePlayer.java
  src/main/java/de/teamlapen/vampirism/util/Helper.java
  src/main/java/de/teamlapen/vampirism/util/Permissions.java
  src/main/resources/assets/vampirism/lang/en_US.lang
Labels: 1.12, enhancement

#452 entityactions (request)
  src/api/java/de/teamlapen/vampirism/api/entity/actions/IEntityActionUser.java
  src/main/java/de/teamlapen/vampirism/entity/EntityVampirism.java
  src/main/java/de/teamlapen/vampirism/entity/hunter/EntityAdvancedHunter.java
  src/main/java/de/teamlapen/vampirism/entity/hunter/EntityBasicHunter.java
  src/main/java/de/teamlapen/vampirism/entity/vampire/EntityAdvancedVampire.java
  src/main/java/de/teamlapen/vampirism/entity/vampire/EntityBasicVampire.java
Labels: enhancement
