Repository TeamLapen/Vampirism, pull requests merged in 2020-07, with the labels that each got.

#710 ModCompat changes
  src/api/java/de/teamlapen/vampirism/api/entity/CaptureEntityEntry.java
  src/api/java/de/teamlapen/vampirism/api/entity/factions/IFaction.java
  src/api/java/de/teamlapen/vampirism/api/entity/factions/IFactionRegistry.java
  src/api/java/de/teamlapen/vampirism/api/entity/factions/IVillageFactionData.java
  src/api/java/de/teamlapen/vampirism/api/entity/player/actions/DefaultAction.java
  src/api/java/de/teamlapen/vampirism/api/entity/player/actions/IAction.java
  src/api/java/de/teamlapen/vampirism/api/entity/player/actions/IActionHandler.java
  src/api/java/de/teamlapen/vampirism/api/entity/player/hunter/DefaultHunterAction.java
  src/api/java/de/teamlapen/vampirism/api/entity/player/skills/DefaultSkill.java
  src/api/java/de/teamlapen/vampirism/api/entity/player/vampire/DefaultVampireAction.java
  src/api/java/de/teamlapen/vampirism/api/event/VampirismVillageEvent.java
  src/api/java/de/teamlapen/vampirism/api/world/ITotem.java
  src/lib/java/de/teamlapen/lib/lib/client/gui/GuiPieMenu.java
  src/main/java/de/teamlapen/vampirism/VampirismMod.java
  src/main/java/de/teamlapen/vampirism/blocks/TotemTopBlock.java
  src/main/java/de/teamlapen/vampirism/client/gui/SelectActionScreen.java
  src/main/java/de/teamlapen/vampirism/core/ModBlocks.java
  src/main/java/de/teamlapen/vampirism/core/ModVillage.java
  src/main/java/de/teamlapen/vampirism/core/ModWorld.java
  src/main/java/de/teamlapen/vampirism/entity/FactionVillagerProfession.java
  src/main/java/de/teamlapen/vampirism/entity/factions/Faction.java
  src/main/java/de/teamlapen/vampirism/entity/factions/FactionRegistry.java
  src/main/java/de/teamlapen/vampirism/entity/factions/PlayableFaction.java
  src/main/java/de/teamlapen/vampirism/player/actions/ActionHandler.java
  src/main/java/de/teamlapen/vampirism/player/skills/ActionSkill.java
  src/main/java/de/teamlapen/vampirism/player/skills/VampirismSkill.java
  src/main/java/de/teamlapen/vampirism/tileentity/TotemTileEntity.java
  src/main/java/de/teamlapen/vampirism/util/HunterVillageData.java
  src/main/java/de/teamlapen/vampirism/util/ModEventFactory.java
  src/main/java/de/teamlapen/vampirism/util/VampireVillageData.java
  src/main/java/de/teamlapen/vampirism/world/gen/util/RandomBlockState.java
  src/main/java/de/teamlapen/vampirism/world/gen/util/RandomStructureProcessor.java
Labels: 1.14, 1.15, modcompat

#730 Feature baron
  src/api/java/de/teamlapen/vampirism/api/entity/IEntityLeader.java
  src/api/java/de/teamlapen/vampirism/api/entity/vampire/IAdvancedVampire.java
  src/api/java/de/teamlapen/vampirism/api/entity/vampire/IVampireBaron.java
  src/main/java/de/teamlapen/vampirism/client/model/BaronAttireModel.java
  src/main/java/de/teamlapen/vampirism/client/model/BaronModel.java
  src/main/java/de/teamlapen/vampirism/client/model/BaronWrapperModel.java
  src/main/java/de/teamlapen/vampirism/client/model/BaronessAttireModel.java
  src/main/java/de/teamlapen/vampirism/client/model/BaronessModel.java
  src/main/java/de/teamlapen/vampirism/client/model/WingModel.java
  src/main/java/de/teamlapen/vampirism/client/render/LayerBaronAttire.java
  src/main/java/de/teamlapen/vampirism/client/render/LayerWings.java
  src/main/java/de/teamlapen/vampirism/client/render/entities/VampireBaronRenderer.java
  src/main/java/de/teamlapen/vampirism/config/BalanceMobProps.java
  src/main/java/de/teamlapen/vampirism/entity/goals/DefendLeaderGoal.java
  src/main/java/de/teamlapen/vampirism/entity/goals/FollowAdvancedVampireGoal.java
  src/main/java/de/teamlapen/vampirism/entity/vampire/BasicVampireEntity.java
  src/main/java/de/teamlapen/vampirism/entity/vampire/VampireBaronEntity.java
  src/main/java/de/teamlapen/vampirism/world/gen/biome/VampireForestBiome.java
  src/main/resources/assets/vampirism/textures/entity/baron.png
  src/main/resources/assets/vampirism/textures/entity/baron_attire.png
  src/main/resources/assets/vampirism/textures/entity/baron_enraged.png
  src/main/resources/assets/vampirism/textures/entity/baroness.png
  src/main/resources/assets/vampirism/textures/entity/baroness_attire.png
  src/main/resources/assets/vampirism/textures/entity/baroness_enraged.png
  src/main/resources/assets/vampirism/textures/entity/vampire_baron.png
  src/main/resources/assets/vampirism/textures/entity/wings.png
Labels: 1.14, enhancement

#728 Replace crossbow infinity with vanilla infinity
  src/main/java/de/teamlapen/vampirism/core/ModEnchantments.java
  src/main/java/de/teamlapen/vampirism/core/RegistryManager.java
  src/main/java/de/teamlapen/vampirism/items/VampirismItemCrossbow.java
  src/main/java/de/teamlapen/vampirism/items/enchantment/EnchantmentArrowFrugality.java
  src/main/java/de/teamlapen/vampirism/items/enchantment/EnchantmentCrossbowInfinite.java
  src/main/resources/data/vampirism/recipes/weapontable/crossbow_arrow_from_vanilla.json
Labels: 1.14, enhancement

#732 [1.14] More textures using the "new" Minecraft style
  dev_resources/textures/coffin_base.png
  dev_resources/textures/coffin_wool_mask.png
  dev_resources/textures/old_coffin_black.png
  src/main/resources/assets/vampirism/textures/block/church_altar.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_black.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_blue.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_brown.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_cyan.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_gray.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_green.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_light_blue.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_light_gray.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_lime.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_magenta.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_orange.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_pink.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_purple.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_red.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_white.png
  src/main/resources/assets/vampirism/textures/block/coffin/coffin_yellow.png
  src/main/resources/assets/vampirism/textures/block/garlic_beacon_side.png
  src/main/resources/assets/vampirism/textures/block/weapon_table_hammer.png
Labels: enhancement

#736 Add JEI "recipe" renderer for task rewards
  src/api/java/de/teamlapen/vampirism/api/entity/player/task/TaskUnlocker.java
  src/main/java/de/teamlapen/vampirism/modcompat/guide/GuideHelper.java
  src/main/java/de/teamlapen/vampirism/modcompat/jei/TaskRecipeCategory.java
  src/main/java/de/teamlapen/vampirism/modcompat/jei/VampirismJEIPlugin.java
  src/main/java/de/teamlapen/vampirism/player/tasks/TaskUtil.java
  src/main/java/de/teamlapen/vampirism/player/tasks/unlock/LvlUnlocker.java
  src/main/java/de/teamlapen/vampirism/player/tasks/unlock/ParentUnlocker.java
  src/main/resources/assets/vampirism/lang/en_us.json
Labels: 1.14, enhancement

#727 Add feeding adapter item to allow feeding from blood container in inv…
  src/main/java/de/teamlapen/vampirism/blocks/BloodContainerBlock.java
  src/main/java/de/teamlapen/vampirism/core/ModItems.java
  src/main/java/de/teamlapen/vampirism/core/ModTasks.java
  src/main/java/de/teamlapen/vampirism/fluids/BloodHelper.java
  src/main/java/de/teamlapen/vampirism/items/FeedingAdapterItem.java
  src/main/java/de/teamlapen/vampirism/modcompat/guide/GuideBook.java
  src/main/java/de/teamlapen/vampirism/modcompat/guide/ItemInfoBuilder.java
  src/main/resources/assets/vampirism/lang/en_us.json
  src/main/resources/assets/vampirism/models/item/feeding_adapter.json
  src/main/resources/assets/vampirism/textures/item/feeding_adapter.png
  src/main/resources/assets/vampirismguide/lang/en_us.json
Labels: 1.14, feature
