Repository TeamLapen/Vampirism, pull requests merged in 2021-04, with the labels that each got.

#860 Reset player and minion skills with ingame elements
  src/api/java/de/teamlapen/vampirism/api/entity/player/skills/ISkillHandler.java
  src/generated/resources/.cache/cache
  src/generated/resources/assets/vampirism/models/item/oblivion_potion.json
  src/lib/java/de/teamlapen/lib/lib/inventory/InventoryHelper.java
  src/main/java/de/teamlapen/vampirism/client/gui/AppearanceScreen.java
  src/main/java/de/teamlapen/vampirism/client/gui/MinionStatsScreen.java
  src/main/java/de/teamlapen/vampirism/client/gui/SkillsScreen.java
  src/main/java/de/teamlapen/vampirism/command/test/SkillCommand.java
  src/main/java/de/teamlapen/vampirism/core/ModEffects.java
  src/main/java/de/teamlapen/vampirism/core/ModItems.java
  src/main/java/de/teamlapen/vampirism/core/ModTasks.java
  src/main/java/de/teamlapen/vampirism/data/ItemModelGenerator.java
  src/main/java/de/teamlapen/vampirism/entity/minion/HunterMinionEntity.java
  src/main/java/de/teamlapen/vampirism/entity/minion/VampireMinionEntity.java
  src/main/java/de/teamlapen/vampirism/entity/minion/management/MinionData.java
  src/main/java/de/teamlapen/vampirism/entity/minion/management/MinionInventory.java
  src/main/java/de/teamlapen/vampirism/items/OblivionItem.java
  src/main/java/de/teamlapen/vampirism/network/InputEventPacket.java
  src/main/java/de/teamlapen/vampirism/player/skills/SkillHandler.java
  src/main/java/de/teamlapen/vampirism/player/tasks/unlock/LvlUnlocker.java
  src/main/java/de/teamlapen/vampirism/potion/OblivionEffect.java
  src/main/resources/assets/vampirism/lang/en_us.json
  src/main/resources/assets/vampirism/textures/gui/reset.png
  src/main/resources/assets/vampirism/textures/item/oblivion_potion.png
  src/main/resources/assets/vampirism/textures/mob_effect/oblivion.png
  src/main/resources/assets/vampirism/textures/mob_effect/oblivion.png.mcmeta
Labels: 1.16, feature

#897 Vampire immortality
  src/api/java/de/teamlapen/vampirism/api/entity/player/vampire/IVampirePlayer.java
  src/main/java/de/teamlapen/vampirism/client/gui/CooldownButton.java
  src/main/java/de/teamlapen/vampirism/client/gui/DBNOScreen.java
  src/main/java/de/teamlapen/vampirism/client/render/RenderHandler.java
  src/main/java/de/teamlapen/vampirism/config/BalanceBuilder.java
  src/main/java/de/teamlapen/vampirism/config/BalanceConfig.java
  src/main/java/de/teamlapen/vampirism/core/ModEffects.java
  src/main/java/de/teamlapen/vampirism/core/ModEventHandler.java
  src/main/java/de/teamlapen/vampirism/entity/CrossbowArrowEntity.java
  src/main/java/de/teamlapen/vampirism/mixin/MixinEntityPredicate.java
  src/main/java/de/teamlapen/vampirism/network/InputEventPacket.java
  src/main/java/de/teamlapen/vampirism/player/ModPlayerEventHandler.java
  src/main/java/de/teamlapen/vampirism/player/vampire/VampirePlayer.java
  src/main/java/de/teamlapen/vampirism/player/vampire/VampirePlayerDefaultImpl.java
  src/main/java/de/teamlapen/vampirism/potion/VampirismEffect.java
  src/main/java/de/teamlapen/vampirism/proxy/ClientProxy.java
  src/main/java/de/teamlapen/vampirism/proxy/IProxy.java
  src/main/java/de/teamlapen/vampirism/util/Helper.java
  src/main/resources/assets/vampirism/lang/en_us.json
  src/main/resources/assets/vampirism/textures/mob_effect/neonatal.png
  src/main/resources/vampirism.mixins.json
Labels: 1.16, discussion, feature

#908 Vampire natural armor
  src/main/java/de/teamlapen/vampirism/config/BalanceConfig.java
  src/main/java/de/teamlapen/vampirism/core/ModEffects.java
  src/main/java/de/teamlapen/vampirism/entity/ModEntityEventHandler.java
  src/main/java/de/teamlapen/vampirism/player/vampire/VampirePlayer.java
  src/main/java/de/teamlapen/vampirism/potion/VampirismEffect.java
  src/main/resources/assets/vampirism/lang/en_us.json
  src/main/resources/assets/vampirism/textures/mob_effect/armor_regeneration.png
Labels: feature
